src/java/entities/Partners.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author haronsoft
 */
@Entity
@Table(name = "partners")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Partners.findAll", query = "SELECT p FROM Partners p"),
    @NamedQuery(name = "Partners.findById", query = "SELECT p FROM Partners p WHERE p.id = :id"),
    @NamedQuery(name = "Partners.findByName", query = "SELECT p FROM Partners p WHERE p.name = :name"),
    @NamedQuery(name = "Partners.findByBasefare", query = "SELECT p FROM Partners p WHERE p.basefare = :basefare"),
    @NamedQuery(name = "Partners.findByKmrate", query = "SELECT p FROM Partners p WHERE p.kmrate = :kmrate"),
    @NamedQuery(name = "Partners.findByTimerate", query = "SELECT p FROM Partners p WHERE p.timerate = :timerate"),
    @NamedQuery(name = "Partners.findByActive", query = "SELECT p FROM Partners p WHERE p.active = :active"),
    @NamedQuery(name = "Partners.findByCreatedAt", query = "SELECT p FROM Partners p WHERE p.createdAt = :createdAt"),
    @NamedQuery(name = "Partners.findByUpdatedAt", query = "SELECT p FROM Partners p WHERE p.updatedAt = :updatedAt")})
public class Partners implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "name")
    private String name;
    @Basic(optional = false)
    @NotNull
    @Column(name = "basefare")
    private double basefare;
    @Basic(optional = false)
    @NotNull
    @Column(name = "kmrate")
    private double kmrate;
    @Basic(optional = false)
    @NotNull
    @Column(name = "timerate")
    private double timerate;
    @Basic(optional = false)
    @NotNull
    @Column(name = "active")
    private boolean active;
    @Basic(optional = false)
    @NotNull
    @Column(name = "created_at")
    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;
    @Basic(optional = false)
    @NotNull
    @Column(name = "updated_at")
    @Temporal(TemporalType.TIMESTAMP)
    private Date updatedAt;
    @JoinColumn(name = "car_specific_model_id", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private CarSpecificModel carSpecificModelId;

    public Partners() {
    }

    public Partners(Integer id) {
        this.id = id;
    }

    public Partners(Integer id, String name, double basefare, double kmrate, double timerate, boolean active, Date createdAt, Date updatedAt) {
        this.id = id;
        this.name = name;
        this.basefare = basefare;
        this.kmrate = kmrate;
        this.timerate = timerate;
        this.active = active;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getBasefare() {
        return basefare;
    }

    public void setBasefare(double basefare) {
        this.basefare = basefare;
    }

    public double getKmrate() {
        return kmrate;
    }

    public void setKmrate(double kmrate) {
        this.kmrate = kmrate;
    }

    public double getTimerate() {
        return timerate;
    }

    public void setTimerate(double timerate) {
        this.timerate = timerate;
    }

    public boolean getActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public CarSpecificModel getCarSpecificModelId() {
        return carSpecificModelId;
    }

    public void setCarSpecificModelId(CarSpecificModel carSpecificModelId) {
        this.carSpecificModelId = carSpecificModelId;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Partners)) {
            return false;
        }
        Partners other = (Partners) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entities.Partners[ id=" + id + " ]";
    }
    
}

src/java/controllers/PartnersController.java
package controllers;

import entities.Partners;
import controllers.util.JsfUtil;
import controllers.util.JsfUtil.PersistAction;
import entities.CarSpecificModel;
import facades.PartnersFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;

@Named("partnersController")
@SessionScoped
public class PartnersController implements Serializable {

    @EJB
    private facades.PartnersFacade ejbFacade;
    private List<Partners> items = null;
    private Partners selected;

    public PartnersController() {
    }

    public Partners getSelected() {
        return selected;
    }

    public void setSelected(Partners selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private PartnersFacade getFacade() {
        return ejbFacade;
    }

    public Partners prepareCreate() {
        selected = new Partners();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("PartnersCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("PartnersUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("PartnersDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Partners> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Partners getPartners(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Partners> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Partners> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Partners.class)
    public static class PartnersControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PartnersController controller = (PartnersController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "partnersController");
            return controller.getPartners(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Partners) {
                Partners o = (Partners) object;
                return getStringKey(o.getId());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Partners.class.getName()});
                return null;
            }
        }

    }
public  List<CarSpecificModel> getSpecificModels(){
    List list;
    EntityManagerFactory emf=Persistence.createEntityManagerFactory("meridegenPU");
    EntityManager em=emf.createEntityManager();
    Query query=em.createNamedQuery("CarSpecificModel.findAll",CarSpecificModel.class);
    list=query.getResultList();
    return list;
}
}

web/partners/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PartnersCreateDlg" widgetVar="PartnersCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreatePartnersTitle}">
            <h:form id="PartnersCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{partnersController.selected != null}">
                        <p:outputLabel value="#{bundle.CreatePartnersLabel_id}" for="id" />
                        <p:inputText id="id" value="#{partnersController.selected.id}" title="#{bundle.CreatePartnersTitle_id}" required="true" requiredMessage="#{bundle.CreatePartnersRequiredMessage_id}"/>
                        <p:outputLabel value="#{bundle.CreatePartnersLabel_name}" for="name" />
                        <p:inputText id="name" value="#{partnersController.selected.name}" title="#{bundle.CreatePartnersTitle_name}" required="true" requiredMessage="#{bundle.CreatePartnersRequiredMessage_name}"/>
                        <p:outputLabel value="#{bundle.CreatePartnersLabel_basefare}" for="basefare" />
                        <p:inputText id="basefare" value="#{partnersController.selected.basefare}" title="#{bundle.CreatePartnersTitle_basefare}" required="true" requiredMessage="#{bundle.CreatePartnersRequiredMessage_basefare}"/>
                        <p:outputLabel value="#{bundle.CreatePartnersLabel_kmrate}" for="kmrate" />
                        <p:inputText id="kmrate" value="#{partnersController.selected.kmrate}" title="#{bundle.CreatePartnersTitle_kmrate}" required="true" requiredMessage="#{bundle.CreatePartnersRequiredMessage_kmrate}"/>
                        <p:outputLabel value="#{bundle.CreatePartnersLabel_timerate}" for="timerate" />
                        <p:inputText id="timerate" value="#{partnersController.selected.timerate}" title="#{bundle.CreatePartnersTitle_timerate}" required="true" requiredMessage="#{bundle.CreatePartnersRequiredMessage_timerate}"/>
                        <p:outputLabel value="#{bundle.CreatePartnersLabel_active}" for="active" />
                        <p:selectBooleanCheckbox id="active" value="#{partnersController.selected.active}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_active}"/>
                        <p:outputLabel value="#{bundle.CreatePartnersLabel_createdAt}" for="createdAt" />
                        <p:calendar id="createdAt" pattern="MM/dd/yyyy HH:mm:ss" value="#{partnersController.selected.createdAt}" title="#{bundle.EditPartnersTitle_createdAt}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_createdAt}" showOn="button"/>
                        <p:outputLabel value="#{bundle.CreatePartnersLabel_updatedAt}" for="updatedAt" />
                        <p:calendar id="updatedAt" pattern="MM/dd/yyyy HH:mm:ss" value="#{partnersController.selected.updatedAt}" title="#{bundle.EditPartnersTitle_updatedAt}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_updatedAt}" showOn="button"/>
                        <p:outputLabel value="#{bundle.CreatePartnersLabel_carSpecificModelId}" for="carSpecificModelId" />
                        <h:selectOneMenu id="carSpecificModelId" value="#{partnersController.selected.carSpecificModelId}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_carSpecificModelId}">
                            <f:selectItems value="#{partnersController.specificModels}"
                                           var="carSpecificModelIdItem"
                                           itemValue="#{carSpecificModelIdItem.id}" itemLabel="#{carSpecificModelIdItem.specificModel}"/>
                                            
                        </h:selectOneMenu>
                        <p:outputLabel value="Car model" for="carModelId" />
                        <h:selectOneMenu id="carModelId" value="#{carModelController.selected.model}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_carSpecificModelId}">
                            <f:selectItems value="#{carModelController.carModel}"
                                           var="carModelIdItem"
                                           itemValue="#{carModelIdItem.id}" itemLabel="#{carModelIdItem.model}"/>
                                            
                        </h:selectOneMenu>
                       
                        
                    </p:panelGrid>
                    <p:commandButton actionListener="#{partnersController.create}" value="#{bundle.Save}" update="display,:PartnersListForm:datalist,:growl" oncomplete="handleSubmit(args,'PartnersCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="PartnersCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/partners/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PartnersEditDlg" widgetVar="PartnersEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditPartnersTitle}">
            <h:form id="PartnersEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{partnersController.selected != null}">
                        <p:outputLabel value="#{bundle.EditPartnersLabel_id}" for="id" />
                        <p:inputText id="id" value="#{partnersController.selected.id}" title="#{bundle.EditPartnersTitle_id}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_id}"/>
                        <p:outputLabel value="#{bundle.EditPartnersLabel_name}" for="name" />
                        <p:inputText id="name" value="#{partnersController.selected.name}" title="#{bundle.EditPartnersTitle_name}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_name}"/>
                        <p:outputLabel value="#{bundle.EditPartnersLabel_basefare}" for="basefare" />
                        <p:inputText id="basefare" value="#{partnersController.selected.basefare}" title="#{bundle.EditPartnersTitle_basefare}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_basefare}"/>
                        <p:outputLabel value="#{bundle.EditPartnersLabel_kmrate}" for="kmrate" />
                        <p:inputText id="kmrate" value="#{partnersController.selected.kmrate}" title="#{bundle.EditPartnersTitle_kmrate}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_kmrate}"/>
                        <p:outputLabel value="#{bundle.EditPartnersLabel_timerate}" for="timerate" />
                        <p:inputText id="timerate" value="#{partnersController.selected.timerate}" title="#{bundle.EditPartnersTitle_timerate}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_timerate}"/>
                        <p:outputLabel value="#{bundle.EditPartnersLabel_active}" for="active" />
                        <p:selectBooleanCheckbox id="active" value="#{partnersController.selected.active}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_active}"/>
                        <p:outputLabel value="#{bundle.EditPartnersLabel_createdAt}" for="createdAt" />
                        <p:calendar id="createdAt" pattern="MM/dd/yyyy HH:mm:ss" value="#{partnersController.selected.createdAt}" title="#{bundle.EditPartnersTitle_createdAt}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_createdAt}" showOn="button"/>
                        <p:outputLabel value="#{bundle.EditPartnersLabel_updatedAt}" for="updatedAt" />
                        <p:calendar id="updatedAt" pattern="MM/dd/yyyy HH:mm:ss" value="#{partnersController.selected.updatedAt}" title="#{bundle.EditPartnersTitle_updatedAt}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_updatedAt}" showOn="button"/>
                        <p:outputLabel value="#{bundle.EditPartnersLabel_carSpecificModelId}" for="carSpecificModelId" />
                        <p:selectOneMenu id="carSpecificModelId" value="#{partnersController.selected.carSpecificModelId}" required="true" requiredMessage="#{bundle.EditPartnersRequiredMessage_carSpecificModelId}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{carSpecificModelController.itemsAvailableSelectOne}"
                                           var="carSpecificModelIdItem"
                                           itemValue="#{carSpecificModelIdItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{partnersController.update}" value="#{bundle.Save}" update="display,:PartnersListForm:datalist,:growl" oncomplete="handleSubmit(args, 'PartnersEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="PartnersEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

web/partners/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/admin/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListPartnersTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        #{bundle.ListBookingsTitle}
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                             <li><h:link class="fa fa-dashboard" outcome="/admin/dashboard.xhtml" value="    Dashboard"/></li>
                        </li>
                        <li class="active">
                            <i class="fa fa-newspaper-o"></i> #{bundle.ListBookingsTitle}
                        </li>
                    </ol>
                </div>
             </div>
            <h:form id="PartnersListForm">
                <p:panel header="#{bundle.ListPartnersTitle}">
                    <p:dataTable id="datalist" value="#{partnersController.items}" var="item"
                                 selectionMode="single" selection="#{partnersController.selected}"
                                 paginator="true"
                                 rowKey="#{item.id}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton "/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton "/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPartnersTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPartnersTitle_name}"/>
                            </f:facet>
                            <h:outputText value="#{item.name}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPartnersTitle_basefare}"/>
                            </f:facet>
                            <h:outputText value="#{item.basefare}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPartnersTitle_kmrate}"/>
                            </f:facet>
                            <h:outputText value="#{item.kmrate}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPartnersTitle_timerate}"/>
                            </f:facet>
                            <h:outputText value="#{item.timerate}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPartnersTitle_active}"/>
                            </f:facet>
                            <p:selectBooleanCheckbox value="#{item.active}" disabled="true"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPartnersTitle_createdAt}"/>
                            </f:facet>
                            <h:outputText value="#{item.createdAt}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPartnersTitle_updatedAt}"/>
                            </f:facet>
                            <h:outputText value="#{item.updatedAt}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPartnersTitle_carSpecificModelId}"/>
                            </f:facet>
                            <h:outputText value="#{item.carSpecificModelId}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{partnersController.prepareCreate}" update=":PartnersCreateForm" oncomplete="PF('PartnersCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":PartnersViewForm" oncomplete="PF('PartnersViewDialog').show()" disabled="#{empty partnersController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":PartnersEditForm" oncomplete="PF('PartnersEditDialog').show()" disabled="#{empty partnersController.selected}"/>
                            
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

web/partners/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="PartnersViewDlg" widgetVar="PartnersViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewPartnersTitle}">
            <h:form id="PartnersViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{partnersController.selected != null}">
                        <h:outputText value="#{bundle.ViewPartnersLabel_id}"/>
                        <h:outputText value="#{partnersController.selected.id}" title="#{bundle.ViewPartnersTitle_id}"/>
                        <h:outputText value="#{bundle.ViewPartnersLabel_name}"/>
                        <h:outputText value="#{partnersController.selected.name}" title="#{bundle.ViewPartnersTitle_name}"/>
                        <h:outputText value="#{bundle.ViewPartnersLabel_basefare}"/>
                        <h:outputText value="#{partnersController.selected.basefare}" title="#{bundle.ViewPartnersTitle_basefare}"/>
                        <h:outputText value="#{bundle.ViewPartnersLabel_kmrate}"/>
                        <h:outputText value="#{partnersController.selected.kmrate}" title="#{bundle.ViewPartnersTitle_kmrate}"/>
                        <h:outputText value="#{bundle.ViewPartnersLabel_timerate}"/>
                        <h:outputText value="#{partnersController.selected.timerate}" title="#{bundle.ViewPartnersTitle_timerate}"/>
                        <h:outputText value="#{bundle.ViewPartnersLabel_active}"/>
                        <p:selectBooleanCheckbox value="#{partnersController.selected.active}" disabled="true"/>
                        <h:outputText value="#{bundle.ViewPartnersLabel_createdAt}"/>
                        <h:outputText value="#{partnersController.selected.createdAt}" title="#{bundle.ViewPartnersTitle_createdAt}">
                            <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewPartnersLabel_updatedAt}"/>
                        <h:outputText value="#{partnersController.selected.updatedAt}" title="#{bundle.ViewPartnersTitle_updatedAt}">
                            <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewPartnersLabel_carSpecificModelId}"/>
                        <h:outputText value="#{partnersController.selected.carSpecificModelId}" title="#{bundle.ViewPartnersTitle_carSpecificModelId}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="PartnersViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>